name: 🚀 Deploy Infra K8s (EKS + S3 + SQS)

on:
  workflow_dispatch: 

env:
  AWS_REGION: us-east-1

jobs:
  terraform-apply:
    name: 🏗 Terraform Apply
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout do código
        uses: actions/checkout@v4

      - name: 🔐 Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} 
          aws-region: ${{ env.AWS_REGION }}

      - name: 🏗 Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: ⚙️ Terraform Init
        run: terraform init
        working-directory: terraform

      - name: 🚀 Terraform Apply
        run: |
          terraform apply -auto-approve \
          -var="terraform_admin_arn=${{ secrets.TERRAFORM_ADMIN_ARN }}"
        working-directory: terraform